services:
  system_monitor:
    build:
        context: ..
        dockerfile: ./docker/Dockerfile
    container_name: system_monitor
    volumes:
      - ../scripts:/app/scripts
      - ../dashboard:/app/dashboard
      - ../reports:/app/reports
      - ../web:/app/web
      # - ./entrypoint.sh:/app/entrypoint.sh
      - ../data:/app/data 
    environment:
      - TZ=Etc/UTC
    command: nodemon --watch /app/web --exec node /app/web/server.js
    # depends_on:
    #   - influxdb
    ports:
      - 8080:8080
    tty: true
    stdin_open: true


  # influxdb:
  #   image: influxdb:1.8
  #   container_name: influxdb
  #   environment:
  #     - INFLUXDB_DB=metrics
  #     - INFLUXDB_ADMIN_ENABLED=true
  #     - INFLUXDB_USER=mrz
  #     - INFLUXDB_USER_PASSWORD=kokomama
  #   volumes:
  #     - influxdb_data:/var/lib/influxdb
  #   ports:
  #     - "8086:8086"

# volumes:
#   influxdb_data:
